[package]
name = "mediawiki"
description = "A MediaWiki client library"
keywords = ["MediaWiki","API"]
categories = ["api-bindings","authentication"]
license = "MIT OR Apache-2.0"
repository = "https://github.com/magnusmanske/mediawiki_rust"
version = "0.2.1"
authors = ["Magnus Manske <magnusmanske@googlemail.com>"]
edition = "2018"

[dependencies]
serde_json = "1"
tokio = { version = "^0.2", features = ["macros"] }
reqwest = { version = "^0.10", features = ["blocking", "cookies", "json"] }
user_agent = "0.11"
urlencoding = "1"
config = "0.10"
cookie = "0.13"
nanoid = "0.3"
url = "2.1"
base64 = "0.12"
hmac = "0.7.1"
sha-1 = "0.8.2"
anyhow = "1"

[dev-dependencies]
lazy_static = "1.4"
