[package]
name = "mediawiki"
description = "A MediaWiki client library"
keywords = ["MediaWiki","API"]
categories = ["api-bindings","authentication"]
license = "MIT OR Apache-2.0"
repository = "https://github.com/magnusmanske/mediawiki_rust"
version = "0.2.6"
authors = ["Magnus Manske <magnusmanske@googlemail.com>"]
edition = "2018"

[dependencies]
serde_json = "^1"
tokio = { version = "^1", features = ["full","rt-multi-thread"] }
reqwest = { version = "^0.11", features = ["blocking", "cookies", "json"] }
futures = "^0.3"
urlencoding = "^1"
config = "^0.10"
nanoid = "^0.3"
url = "^2.2"
base64 = "^0.13"
hmac = "^0.10.1"
md5 = "^0.7.0"
sha2 = "^0.9.2"

[dev-dependencies]
lazy_static = "^1.4"
